config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout, via: :delete
  resources :properties

  root 'properties#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord

  has_many :key_features, dependent: :destroy
  has_many :properties, through: :key_features

end

app/models/floor_plan.rb
class FloorPlan < ApplicationRecord
  belongs_to :property

  paperclip_opts = {
    :styles => { :thumb => '40x40#', :medium => '150x200>', :large => '300x300>' },
    :convert_options => { :all => '-quality 92' },
    :processor       => [ :cropper ]
  }

  unless Rails.env.development?
    paperclip_opts.merge! :storage        => :s3,
                          :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
                          :path           => ':attachment/:id/:style.:extension',
                          :bucket         => 'property_uploads'
  end

  has_attached_file :image, paperclip_opts
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/key_feature.rb
class KeyFeature < ApplicationRecord

  belongs_to :feature
  belongs_to :property

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :property

  paperclip_opts = {
    :styles => { :thumb => '40x40#', :medium => '150x200>', :large => '300x300>' },
    :convert_options => { :all => '-quality 92' },
    :processor       => [ :cropper ]
  }

  unless Rails.env.development?
    paperclip_opts.merge! :storage        => :s3,
                          :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
                          :path           => ':attachment/:id/:style.:extension',
                          :bucket         => 'property_uploads'
  end

  has_attached_file :image, paperclip_opts

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/property.rb
class Property < ApplicationRecord

  has_many :key_features, dependent: :destroy
  has_many :features, through: :key_features
  has_many :photos, dependent: :destroy
  has_many :floor_plans, dependent: :destroy

  validates :address, presence: true

  def add_photos(photo_params)
    photos = photo_params[:image].map { |img| self.photos.build(Hash[:image => img]) } unless photo_params.empty?
    self.photos << photos unless photos.nil?
  end

  def add_floor_plans(floor_plan_params)
    floor_plans = floor_plan_params[:image]
      .map { |img| self.floor_plans.build(Hash[:image => img]) } unless floor_plan_params.empty?
    self.floor_plans << floor_plans unless floor_plans.nil?
  end

  def add_key_features(key_feature_params)
    key_features = key_feature_params[:key_features]
    key_features.shift

    key_features.each do |kf|
      feature = Feature.find(kf)
      key_feature = self.key_features.build
      feature.key_features << key_feature
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.name,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.order(:id).page params[:page]
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @photo = Photo.new
    @floor_plan = FloorPlan.new
    @property = @photo.build_property
  end

  def create
    @property = Property.new(property_params)

    if @property.save
      @property.add_photos(photo_params)
      @property.add_floor_plans(floor_plan_params)
      @property.add_key_features(key_feature_params)

      redirect_to properties_path
    end
  end

  private

  def photo_params
    params.fetch(:photo,{}).permit(:image => [])
  end

  def floor_plan_params
    params.fetch(:floor_plan,{}).permit(:image => [])
  end

  def key_feature_params
    params.fetch(:property,{}).permit(:key_features => [])
  end

  def property_params
    params.fetch(:property).permit(:description, :address, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyListing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyGFo6FC9QDVmr4Eg9trsgZFj9CXFlSiA" type="text/javascript"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCyGFo6FC9QDVmr4Eg9trsgZFj9CXFlSiA"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <% if current_user %>
            <p class="navbar-text navbar-right">Welcome, <%= current_user.name %>!</p>
            <%= link_to "Sign Out", signout_path, method: :delete, class: 'navbar-brand' %>
          <% else %>
            <a class="navbar-brand" href="/auth/twitter">Sign in with Twitter</a>
          <% end %>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= simple_form_for(@property, html: {multipart: true}) do |f| %>
  <div class="form-group">
    <%= f.input :address, :input_html =>{:id => 'gmaps-input-address'}, :placeholder => 'Start typing a place...', required: true  %>
  </div>
  <div class="form-group">
    <%= f.input :price, required: true %>
  </div>
  <div class="form-group">
    <%= f.input :description, required: true %>
  </div>
  <div class="form-group">
    <%= f.input :key_features, :collection => Feature.all, input_html: { multiple: true } %>
  </div>
  <div class="form-group">
    <label for="photos">Property photos</label>
    <%= simple_fields_for @photo do |o| %>
      <%= o.input :image, as: :file, input_html: {multiple: true, id: "photos"} %>
    <% end %>
  </div>
  <div class="form-group">
    <label for="floor-plan">Floor plans</label>
    <%= simple_fields_for @floor_plan do |o| %>
      <%= o.input :image, as: :file, input_html: {multiple: true, id: "floor-plan"} %>
    <% end %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/properties/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/properties/index.html.erb
<div class="container text-center">
  <h2 class="text-center">Properties list</h2>
  <%= link_to 'Add Property', new_property_path, class: 'btn btn-primary' %>
  <% @properties.each do |p| %>
    <div class="row">
      <div class="col-md-6">
      <div class="row">
        <div class="col-md-2">
          <h3 class="bold lead"><strong>Description:</strong></h3>
        </div>
        <div class="col-md-10">
          <h3 class="lead"><%= p.description %></h3>
        </div>
        <div class="col-md-2">
          <h3 class="bold lead"><strong>Price:</strong></h3>
        </div>
        <div class="col-md-10">
          <h3 class="lead"><%= number_to_currency(p.price) %></h3>
        </div>
        <div class="col-md-4">
          <%= link_to 'See details', property_path(p) %>
        </div>
      </div>
      </div>
      <div class="col-md-6">
        <%= image_tag Faker::Avatar.image, class: 'img_responsive', style: "height: 300px;" %>
      </div>
    </div>
  <% end %>
  <%= paginate @properties %>
</div>

app/views/properties/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/properties/show.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#images">Images</a></li>
    <li><a data-toggle="tab" href="#key-features">Key Features</a></li>
    <li><a data-toggle="tab" href="#floor-plan">Floor Plan</a></li>
    <li><a data-toggle="tab" href="#map">Map</a></li>
  </ul>

  <div class="tab-content">
    <div id="images" class="tab-pane fade in ">
      <h3>Property Photos</h3>
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <% @property.photos.each do |photo| %>
          <div class="item">
            <%= image_tag Faker::Avatar.image, class: 'img-responsive' %>
          </div>
          <% end %>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div id="key-features" class="tab-pane fade">
      <h3>Key Features</h3>
      <ul>
      <% @property.features.each do |feature| %>
        <li class="lead">
          <%= feature.title %>
        </li>
      <% end %>
      </ul>
    </div>
    <div id="floor-plan" class="tab-pane fade in">
      <h3>Floor Plan</h3>
      <% @property.floor_plans.each do |photo| %>
        <%= image_tag Faker::Avatar.image, class: 'img-responsive' %>
      <% end %>
      </div>

    <div id="map" class="tab-pane fade">
      <h3>Map View</h3>
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d10167.209455195305!2d30.479902250000002!3d50.4261538!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sru!4v1488206553350" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    </div>
  </div>
</div>